### ISSUE TITLE
how to know which persons are in specific cliques ?

### ISSUE THREAD

**Issue by huguyuehuhu** [mostafa-saad/hierarchical-relational-network#1]
Hi, thanks for your nice work.  When a graph is specified (Fig.3 in your paper),  how to know which persons are in specific cliques ? Is it determined by the location in each frame , but the persons are moving all the way.

**Comment by mostafa-saad** [comment]
This is greedily determined from the first frame. we sort the positions (x, y). Say a clique of 3 persons. Sweep from top left, the first 3 persons are clique one. 

This is definitely could be buggy in some cases, but we think it is ok in many cases. You may develop more sophisticated algorithms.

**Comment by huguyuehuhu** [comment]
Thank you for the reply!
